import { Injectable } from '@angular/core';
import { BehaviorSubject } from 'rxjs';

export type Role = 'user' | 'admin' | 'guest' | 'super';

@Injectable({ providedIn: 'root' })
export class AuthService {
  private authenticatedSubject = new BehaviorSubject<boolean>(false);
  isAuthenticated$ = this.authenticatedSubject.asObservable();

  private rolesSubject = new BehaviorSubject<Role[]>(['guest']);
  roles$ = this.rolesSubject.asObservable();

  private readonly STORAGE_KEY = 'auth_session';

  constructor() {
    // try to restore session from localStorage
    try {
      const raw = localStorage.getItem(this.STORAGE_KEY);
      if (raw) {
        const obj = JSON.parse(raw);
        if (obj && obj.authenticated) {
          this.authenticatedSubject.next(true);
          this.rolesSubject.next(obj.roles || ['guest']);
        }
      }
    } catch (e) {
      // ignore
    }
  }

  // scaffold: real implementation would call backend and set JWT etc.
  // For developer convenience we provide a static `super` user with an
  // autogenerated password stored in localStorage under `super_dev_password`.
  async login(username: string, password: string): Promise<void> {
    // support super user
    if (username === 'super') {
      const pw = this.getOrCreateSuperPassword();
      if (password === pw) {
        this.authenticatedSubject.next(true);
        this.rolesSubject.next(['super']);
        this._persistSession(true, ['super']);
        return;
      }
      return Promise.reject(new Error('Invalid username or password'));
    }

    // fallback: check a lightweight dev user store (localStorage)
    try {
      const raw = localStorage.getItem('dev_users');
      const users = raw ? JSON.parse(raw) : {};
      const entry = users[username];
      if (entry && entry.password === password) {
        const roles = entry.roles || ['user'];
        this.authenticatedSubject.next(true);
        this.rolesSubject.next(roles);
        this._persistSession(true, roles, username);
        return;
      }
    } catch (e) {
      // ignore parse errors
    }

    return Promise.reject(new Error('Invalid username or password'));
  }

  // Return the autogenerated super password (create one if missing)
  getOrCreateSuperPassword(): string {
    try {
      const key = 'super_dev_password';
      let pw = localStorage.getItem(key);
      if (!pw) {
        pw = this._generatePassword(12);
        localStorage.setItem(key, pw);
      }
      return pw;
    } catch (e) {
      // fallback deterministic password if storage unavailable
      return 'super-default';
    }
  }

  // Change roles of a user in the local dev store. Returns true if successful.
  changeUserRoles(username: string, roles: Role[]): boolean {
    try {
      const raw = localStorage.getItem('dev_users');
      const users = raw ? JSON.parse(raw) : {};
      if (!users[username]) return false;
      users[username].roles = roles;
      localStorage.setItem('dev_users', JSON.stringify(users));
      return true;
    } catch (e) {
      return false;
    }
  }

  // Reset a user's password in the local dev store. Returns new password or null.
  resetUserPassword(username: string): string | null {
    try {
      const raw = localStorage.getItem('dev_users');
      const users = raw ? JSON.parse(raw) : {};
      if (!users[username]) return null;
      const newPw = this._generatePassword(10);
      users[username].password = newPw;
      localStorage.setItem('dev_users', JSON.stringify(users));
      return newPw;
    } catch (e) {
      return null;
    }
  }

  logout(): void {
    this.authenticatedSubject.next(false);
    this.rolesSubject.next(['guest']);
    try { localStorage.removeItem(this.STORAGE_KEY); } catch { }
  }

  // helper for tests / dev: set roles
  _setRoles(roles: Role[]): void {
    this.rolesSubject.next(roles);
    try { this._persistSession(this.authenticatedSubject.value, roles); } catch { }
  }

  private _persistSession(authenticated: boolean, roles: Role[], username?: string): void {
    try {
      const obj: any = { authenticated, roles };
      if (username) obj.username = username;
      localStorage.setItem(this.STORAGE_KEY, JSON.stringify(obj));
    } catch (e) { /* ignore */ }
  }

  private _generatePassword(len: number): string {
    const chars = 'abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!@#$%^&*()';
    let out = '';
    for (let i = 0; i < len; i++) {
      out += chars.charAt(Math.floor(Math.random() * chars.length));
    }
    return out;
  }
}
